### ISSUE TITLE
AWS Credentials

### ISSUE THREAD

**Issue by jmadda** [multiplegeorges/vue-cli-plugin-s3-deploy#22]
My builds were working a few hour ago, and suddenly I'm getting the a credentials error since the new release.

Error: ENOENT: no such file or directory, open '/root/.aws/credentials'
 ERROR  CredentialsError: Missing credentials in config
CredentialsError: Missing credentials in config
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at Object.readFileSync (/opt/atlassian/pipelines/agent/build/node_modules/aws-sdk/lib/util.js:97:26)
    at SharedIniFile.loadFile [as ensureFileLoaded] (/opt/atlassian/pipelines/agent/build/node_modules/aws-sdk/lib/shared_ini.js:19:18)
    at SharedIniFile.loadProfileNames [as getProfiles] (/opt/atlassian/pipelines/agent/build/node_modules/aws-sdk/lib/shared_ini.js:61:10)
    at SharedIniFileCredentials.refresh (/opt/atlassian/pipelines/agent/build/node_modules/aws-sdk/lib/credentials/shared_ini_file_credentials.js:114:45)
    at SharedIniFileCredentials.get (/opt/atlassian/pipelines/agent/build/node_modules/aws-sdk/lib/credentials.js:121:12)
    at getAsyncCredentials (/opt/atlassian/pipelines/agent/build/node_modules/aws-sdk/lib/config.js:334:24)
    at Config.getCredentials (/opt/atlassian/pipelines/agent/build/node_modules/aws-sdk/lib/config.js:354:9)
    at Request.VALIDATE_CREDENTIALS (/opt/atlassian/pipelines/agent/build/node_modules/aws-sdk/lib/event_listeners.js:80:26)

I'm doing my builds via pipelines in BitBucket, and I've set my AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY via environment variables.

**Comment by multiplegeorges** [comment]
@jmadda I've rolled back the credentials change and added some docs for people using the `.aws/credentials` file.

Your set up should be working again.
