### ISSUE TITLE
visitAssignmentExpression error after running the plugin for the first time.

### ISSUE THREAD

**Issue by erickwilder** [multiplegeorges/vue-cli-plugin-s3-deploy#42]
After adding the plugin and going through the wizard to setup all AWS settings the following error happened:

```
🚀  Invoking generator for vue-cli-plugin-s3-deploy...
 ERROR  Error: Must either call this.traverse or return false in visitAssignmentExpression
Error: Must either call this.traverse or return false in visitAssignmentExpression
    at Context.invokeVisitorMethod (/Users/erickwilder/.nvm/versions/node/v10.12.0/lib/node_modules/@vue/cli/node_modules/ast-types/lib/path-visitor.js:365:21)
    at Visitor.PVp.visitWithoutReset (/Users/erickwilder/.nvm/versions/node/v10.12.0/lib/node_modules/@vue/cli/node_modules/ast-types/lib/path-visitor.js:196:32)
    at visitChildren (/Users/erickwilder/.nvm/versions/node/v10.12.0/lib/node_modules/@vue/cli/node_modules/ast-types/lib/path-visitor.js:246:25)
    at Visitor.PVp.visitWithoutReset (/Users/erickwilder/.nvm/versions/node/v10.12.0/lib/node_modules/@vue/cli/node_modules/ast-types/lib/path-visitor.js:204:20)
    at NodePath.each (/Users/erickwilder/.nvm/versions/node/v10.12.0/lib/node_modules/@vue/cli/node_modules/ast-types/lib/path.js:101:26)
    at visitChildren (/Users/erickwilder/.nvm/versions/node/v10.12.0/lib/node_modules/@vue/cli/node_modules/ast-types/lib/path-visitor.js:219:18)
    at Visitor.PVp.visitWithoutReset (/Users/erickwilder/.nvm/versions/node/v10.12.0/lib/node_modules/@vue/cli/node_modules/ast-types/lib/path-visitor.js:204:20)
    at visitChildren (/Users/erickwilder/.nvm/versions/node/v10.12.0/lib/node_modules/@vue/cli/node_modules/ast-types/lib/path-visitor.js:246:25)
    at Visitor.PVp.visitWithoutReset (/Users/erickwilder/.nvm/versions/node/v10.12.0/lib/node_modules/@vue/cli/node_modules/ast-types/lib/path-visitor.js:204:20)
    at visitChildren (/Users/erickwilder/.nvm/versions/node/v10.12.0/lib/node_modules/@vue/cli/node_modules/ast-types/lib/path-visitor.js:246:25)
```

I'm using node@v10.12.0(with nvm). This is the first time I see something like this and I had no luck trying to solve it myself. I'm not sure if this is an error with s3-deploy or Vue CLI itself, but since I'm not experiencing the same with other plugins I'm reporting here first.

**Comment by erickwilder** [comment]
After a bit more of an investigation, I could make it work but at the cost of losing all customizations made on `vue.config.js` 

To reproduce:

* Given you already have a `vue.config.js` with some customizations made to it.
* Try to add the `s3-deploy` plugin.

I'm still not sure about if this is an error with Vue CLI (it seems so).

**Comment by alexandernst** [comment]
I just hit this error too.

**Comment by JOHNBASS** [comment]
me too.

**Comment by frankisans** [comment]
In my case the error gets if I computed a env variable in vue.config.js:
Removing or commenting the first line solve the problem.

```js
process.env.VUE_APP_VERSION = require("./package.json").version;

module.exports = {
  pluginOptions: {
    s3Deploy: {
       ...
    }
  },
};
```
 Exists an issue in VUE CLI 3 that refers to that problem: https://github.com/vuejs/vue-cli/pull/2770

**Comment by nicekiwi** [comment]
This shoudl be resolved now that vue-cli has fixed the issue on their end.
