### ISSUE TITLE
ERROR  ReferenceError: stopSpinner is not defined

### ISSUE THREAD

**Issue by jkwasniak** [multiplegeorges/vue-cli-plugin-s3-deploy#52]
When using the plugin I get (i use CloudFront -> VUE_APP_S3D_ENABLE_CLOUDFRONT=true) the following error message:

```
✔ All 89 assets have been successfully deployed to https://s3-eu-central-1.amazonaws.com/www.xxxxxxx.de/
⠋ Invalidating CloudFront distribution: YYYYYYYYYYYY INFO  Deployment complete.
✔ Invalidating CloudFront distribution: YYYYYYYYYYYY
 INFO  Invalidation ID: IXXYYXXYYXXYYXX
 INFO  Status: InProgress
 INFO  Call Reference: vue-cli-plugin-s3-deploy-1545478460895
 INFO  See your AWS console for on-going status on this invalidation.
 ERROR  ReferenceError: stopSpinner is not defined
ReferenceError: stopSpinner is not defined
    at invalidateDistribution (....../node_modules/vue-cli-plugin-s3-deploy/s3deploy.js:180:5)
    at process.internalTickCallback (internal/process/next_tick.js:77:7)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

i use :

```
"vue": "^2.5.21",
"@vue/cli-service": "^3.2.0",
"vue-cli-plugin-s3-deploy": "git://github.com/multiplegeorges/vue-cli-plugin-s3-deploy.git#master"
"vue-template-compiler": "^2.5.21"
```

**Comment by nicekiwi** [comment]
Hmmm this is awkward..

**Comment by frankisans** [comment]
Just change to spinner.stop()

```js
    error(`AWS Request ID: ${err.requestId}`)
    throw err
  } finally {
    spinner.stop()
  }
}
```
