### ISSUE TITLE
Error: (undefined/undefined)

### ISSUE THREAD

**Issue by AaronVasquez** [multiplegeorges/vue-cli-plugin-s3-deploy#62]
When I run `yarn deploy`, I get the error below. When I run `aws s3 sync` with the same credentials, I am able to do so successfully. 

```bash
 ERROR  Upload failed: img/icons/safari-pinned-tab.svg
 ERROR  Error: (undefined/undefined) Upload failed: /img/icons/safari-pinned-tab.svg. AWS Error: AccessDenied: Access Denied.
 ERROR  Upload failed: img/icons/msapplication-icon-144x144.png
 ERROR  Error: (undefined/undefined) Upload failed: /img/icons/msapplication-icon-144x144.png. AWS Error: AccessDenied: Access Denied.
 ERROR  Upload failed: img/icons/mstile-150x150.png
 ERROR  Error: (undefined/undefined) Upload failed: /img/icons/mstile-150x150.png. AWS Error: AccessDenied: Access Denied.
 ERROR  Upload failed: img/icons/favicon-32x32.png
 ERROR  Error: (undefined/undefined) Upload failed: /img/icons/favicon-32x32.png. AWS Error: AccessDenied: Access Denied.
 ERROR  Upload failed: img/icons/favicon-16x16.png
 ERROR  Error: (undefined/undefined) Upload failed: /img/icons/favicon-16x16.png. AWS Error: AccessDenied: Access Denied.
 ERROR  Upload failed: img/icons/apple-touch-icon-76x76.png
 ERROR  Error: (undefined/undefined) Upload failed: /img/icons/apple-touch-icon-76x76.png. AWS Error: AccessDenied: Access Denied.
 ERROR  Upload failed: img/icons/apple-touch-icon-60x60.png
 ERROR  Error: (undefined/undefined) Upload failed: /img/icons/apple-touch-icon-60x60.png. AWS Error: AccessDenied: Access Denied.
 ERROR  Upload failed: img/icons/apple-touch-icon.png
 ERROR  Error: (undefined/undefined) Upload failed: /img/icons/apple-touch-icon.png. AWS Error: AccessDenied: Access Denied.
 ERROR  Upload failed: img/icons/apple-touch-icon-180x180.png
 ERROR  Error: (undefined/undefined) Upload failed: /img/icons/apple-touch-icon-180x180.png. AWS Error: AccessDenied: Access Denied.
 ERROR  Upload failed: img/icons/apple-touch-icon-120x120.png
 ERROR  Error: (undefined/undefined) Upload failed: /img/icons/apple-touch-icon-120x120.png. AWS Error: AccessDenied: Access Denied.
 ERROR  Upload failed: img/icons/android-chrome-512x512.png
 ERROR  Error: (undefined/undefined) Upload failed: /img/icons/android-chrome-512x512.png. AWS Error: AccessDenied: Access Denied.
 ERROR  Upload failed: js/index.4db99c82.js.map
 ERROR  Error: (undefined/undefined) Upload failed: /js/index.4db99c82.js.map. AWS Error: AccessDenied: Access Denied.
 ERROR  Upload failed: js/index.4db99c82.js
 ERROR  Error: (undefined/undefined) Upload failed: /js/index.4db99c82.js. AWS Error: AccessDenied: Access Denied.
 ERROR  Upload failed: js/chunk-vendors.a9e60c8b.js.map
 ERROR  Error: (undefined/undefined) Upload failed: /js/chunk-vendors.a9e60c8b.js.map. AWS Error: AccessDenied: Access Denied.
 ERROR  Upload failed: img/icons/android-chrome-192x192.png
 ERROR  Error: (undefined/undefined) Upload failed: /img/icons/android-chrome-192x192.png. AWS Error: AccessDenied: Access Denied.
 ERROR  Upload failed: img/icons/apple-touch-icon-152x152.png
 ERROR  Error: (undefined/undefined) Upload failed: /img/icons/apple-touch-icon-152x152.png. AWS Error: AccessDenied: Access Denied.
 ERROR  Upload failed: css/index.97c32481.css
 ERROR  Error: (undefined/undefined) Upload failed: /css/index.97c32481.css. AWS Error: AccessDenied: Access Denied.
 ERROR  Upload failed: js/chunk-vendors.a9e60c8b.js
 ERROR  Error: (undefined/undefined) Upload failed: /js/chunk-vendors.a9e60c8b.js. AWS Error: AccessDenied: Access Denied.
 ERROR  Upload failed: service-worker.js
 ERROR  Error: (undefined/undefined) Upload failed: /service-worker.js. AWS Error: AccessDenied: Access Denied.
 ERROR  Upload failed: css/chunk-vendors.a526b08d.css
 ERROR  Error: (undefined/undefined) Upload failed: /css/chunk-vendors.a526b08d.css. AWS Error: AccessDenied: Access Denied.
 ERROR  Upload failed: robots.txt
 ERROR  Error: (undefined/undefined) Upload failed: /robots.txt. AWS Error: AccessDenied: Access Denied.
 ERROR  Upload failed: precache-manifest.4b88741b864d65c3ef6a15b8c4803530.js
 ERROR  Error: (undefined/undefined) Upload failed: /precache-manifest.4b88741b864d65c3ef6a15b8c4803530.js. AWS Error: AccessDenied: Access Denied.
 ERROR  Upload failed: manifest.json
 ERROR  Error: (undefined/undefined) Upload failed: /manifest.json. AWS Error: AccessDenied: Access Denied.
 ERROR  Upload failed: index.html
 ERROR  Error: (undefined/undefined) Upload failed: /index.html. AWS Error: AccessDenied: Access Denied.
 ERROR  Upload failed: favicon.ico
 ERROR  Error: (undefined/undefined) Upload failed: /favicon.ico. AWS Error: AccessDenied: Access Denied.
 ERROR  Upload failed: error.html
 ERROR  Error: (undefined/undefined) Upload failed: /error.html. AWS Error: AccessDenied: Access Denied.
 INFO  Deployment complete.
 ERROR  TypeError: Cannot read property 'split' of undefined
TypeError: Cannot read property 'split' of undefined
    at invalidateDistribution (/home/avasquez/Developer/data-console/web/node_modules/vue-cli-plugin-s3-deploy/s3deploy.js:96:56)
    at module.exports (/home/avasquez/Developer/data-console/web/node_modules/vue-cli-plugin-s3-deploy/s3deploy.js:236:7)
    at process._tickCallback (internal/process/next_tick.js:68:7)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by tylergets** [comment]
Also getting this error when using an assumed role as defined here: https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-role.html

**Comment by vikahl** [comment]
I am also getting this error. AWS cli works without problems but I cannot deploy from this script.

Nothing special configured on my part, using default profile.
Not sure if this is an issue with the tool or my AWS settings, but  any help would be appreciated :)

**Comment by Roriz** [comment]
I have the same issue and resolved with `acl: 'private'`. In my case, we want to force a user to consume all files from CloudFront.
