### ISSUE TITLE
esprima unexpected identifier

### ISSUE THREAD

**Issue by saiqulhaq** [multiplegeorges/vue-cli-plugin-s3-deploy#75]
please help generator doesn't work
no clear error message

```
? Create bucket if it does not exist? Yes
? Enable Static Site Hosting on bucket? Yes
? Filename of static index page: index.html
? Filename of static error page: index.html
? Where are your built files? dist
? Which files should be deployed? **
? Where in the bucket should the files be deployed? /
? Which Access Control List (ACL) setting should be applied to deployed files? public-read
? Enable PWA deploy (disables caching of certain files) options? No
? Enable invalidation of a CloudFront distribution on deploy? No

🚀  Invoking generator for vue-cli-plugin-s3-deploy...

 ERROR  Error: Line 19: Unexpected identifier
Error: Line 19: Unexpected identifier
    at ErrorHandler.constructError (/Users/xxx/.config/yarn/global/node_modules/esprima/dist/esprima.js:5012:22)
    at ErrorHandler.createError (/Users/xxx/.config/yarn/global/node_modules/esprima/dist/esprima.js:5028:27)
    at Parser.unexpectedTokenError (/Users/xxx/.config/yarn/global/node_modules/esprima/dist/esprima.js:1985:39)
    at Parser.throwUnexpectedToken (/Users/xxx/.config/yarn/global/node_modules/esprima/dist/esprima.js:1995:21)
    at Parser.expect (/Users/xxx/.config/yarn/global/node_modules/esprima/dist/esprima.js:2168:19)
    at Parser.parseArrayInitializer (/Users/xxx/.config/yarn/global/node_modules/esprima/dist/esprima.js:2427:27)
    at Parser.inheritCoverGrammar (/Users/xxx/.config/yarn/global/node_modules/esprima/dist/esprima.js:2285:37)
    at Parser.parsePrimaryExpression (/Users/xxx/.config/yarn/global/node_modules/esprima/dist/esprima.js:2351:38)
    at Parser.inheritCoverGrammar (/Users/xxx/.config/yarn/global/node_modules/esprima/dist/esprima.js:2285:37)
    at Parser.parseLeftHandSideExpressionAllowCall (/Users/xxx/.config/yarn/global/node_modules/esprima/dist/esprima.js:2899:26)
```

**Comment by Prateema1** [comment]
I got the same exception thrown. It was working perfectly fine for some time but suddenly it threw "Unexpected identifier" error message.
