### ISSUE TITLE
Error: EISDIR: illegal operation on a directory, open 

### ISSUE THREAD

**Issue by aranmohyeddin** [multiplegeorges/vue-cli-plugin-s3-deploy#77]
I installed with ` npm  add vue-cli-plugin-s3-deploy` then I run `vue invoke s3-deploy` after I answer all the questions I get:
```

🚀  Invoking generator for vue-cli-plugin-s3-deploy...
 ERROR  Error: EISDIR: illegal operation on a directory, open 'current dir where pakcage.json is located'
Error: EISDIR: illegal operation on a directory, open 'current dir'
    at Object.openSync (fs.js:448:3)
    at Object.writeFileSync (fs.js:1210:35)
    at Object.keys.forEach (/home/me/.local/lib/node_modules/@vue/cli/lib/util/writeFileTree.js:25:8)
    at Array.forEach (<anonymous>)
    at writeFileTree (/home/me/.local/lib/node_modules/@vue/cli/lib/util/writeFileTree.js:22:22)
```

**Comment by nicekiwi** [comment]
@aranmohyeddin try deleting yarn.lock and try again.
