### ISSUE TITLE
Error: Line 8: Unexpected token ...

### ISSUE THREAD

**Issue by pRizz** [multiplegeorges/vue-cli-plugin-s3-deploy#91]
After completing the wizard, I get an error

```
Invoking generator for vue-cli-plugin-s3-deploy...
 ERROR  Error: Line 8: Unexpected token ...
Error: Line 8: Unexpected token ...
    at ErrorHandler.constructError (/usr/local/lib/node_modules/@vue/cli/node_modules/esprima/dist/esprima.js:5012:22)
    at ErrorHandler.createError (/usr/local/lib/node_modules/@vue/cli/node_modules/esprima/dist/esprima.js:5028:27)
    at Parser.unexpectedTokenError (/usr/local/lib/node_modules/@vue/cli/node_modules/esprima/dist/esprima.js:1985:39)
    at Parser.throwUnexpectedToken (/usr/local/lib/node_modules/@vue/cli/node_modules/esprima/dist/esprima.js:1995:21)
    at Parser.parseObjectPropertyKey (/usr/local/lib/node_modules/@vue/cli/node_modules/esprima/dist/esprima.js:2499:33)
    at Parser.parseObjectProperty (/usr/local/lib/node_modules/@vue/cli/node_modules/esprima/dist/esprima.js:2534:25)
    at Parser.parseObjectInitializer (/usr/local/lib/node_modules/@vue/cli/node_modules/esprima/dist/esprima.js:2602:35)
    at Parser.inheritCoverGrammar (/usr/local/lib/node_modules/@vue/cli/node_modules/esprima/dist/esprima.js:2285:37)
    at Parser.parsePrimaryExpression (/usr/local/lib/node_modules/@vue/cli/node_modules/esprima/dist/esprima.js:2354:38)
    at Parser.inheritCoverGrammar (/usr/local/lib/node_modules/@vue/cli/node_modules/esprima/dist/esprima.js:2285:37)

```

Using latest plugin on latest MacOS

**Comment by nicekiwi** [comment]
@pRizz which commands did you use to get to this? Fresh project?

**Comment by pRizz** [comment]
I was following the installation commands. I just tried again on `4.0.0-rc3` and it still happens during the last step of  `vue invoke s3-deploy`:
```
🚀  Invoking generator for vue-cli-plugin-s3-deploy...
 ERROR  Error: Line 8: Unexpected token ...
...
```

This was on an old project. I can try on a fresh project.

**Comment by pRizz** [comment]
I figured out the issue. My current `vue.config.js` file is using the spread operator `...`

It seems like one of the dependencies (`esprima `) won't parse that.

**Comment by nicekiwi** [comment]
Yeah, I don't think the vue-cli will play nice with the spread operator.

**Comment by pRizz** [comment]
Interesting. It works ok for `vue-cli-service serve` and `vue-cli-service build`.

**Comment by nicekiwi** [comment]
@pRizz oh, hmm. Can you share your vue.config.js file with the spread operator? :)

**Comment by pRizz** [comment]
It basically looks like this

```
const appConfig = {
  VUE_APP_TITLE: "Redacted",
  VUE_APP_URL: "Redacted",
  VUE_APP_SOCIAL_IMAGE: "Redacted",
  VUE_APP_DESCRIPTION: "Redacted"
}

process.env = {...process.env, ...appConfig}
```

**Comment by nicekiwi** [comment]
@pRizz that's not the config file though is it? AFAIK the env variables are not processed in the vue.config.js file.

**Comment by nicekiwi** [comment]
@pRizz can you push a public repo that reproduces this issue? Cause I'm quite lost at this point
